name: crop-loss-EPAR
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- matplotlib=2.2.2
- rasterio
- numpy
- pandas=0.23.3
- pyshp=1.2.11
- basemap=1.0.7
- pip:
  - rasterfoundry[notebook]
  - descarteslabs[complete]
